### ISSUE TITLE
TypeError: Property internalSlots expected type of array but got boolean

### ISSUE THREAD

**Issue by natramov** [PassFort/json-schema-to-flow-type#27]
Hi, in version 0.4.0 i get this type error:

`TypeError: Property internalSlots expected type of array but got boolean
    at validate (/Users/admin/WebstormProjects/flow-swagger/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at Object.validate (/Users/admin/WebstormProjects/flow-swagger/node_modules/@babel/types/lib/definitions/utils.js:172:7)
    at validate (/Users/admin/WebstormProjects/flow-swagger/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/Users/admin/WebstormProjects/flow-swagger/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at ObjectTypeAnnotation (/Users/admin/WebstormProjects/flow-swagger/node_modules/@babel/types/lib/builders/generated/index.js:649:31)
    at processObjectSchema (/Users/admin/WebstormProjects/flow-swagger/node_modules/json-schema-to-flow-type/lib/FlowTypeGenerator.js:43:12)
    at exports.toFlowType.flowSchema (/Users/admin/WebstormProjects/flow-swagger/node_modules/json-schema-to-flow-type/lib/FlowTypeGenerator.js:60:12)
    at exports.toFlow.flowSchema (/Users/admin/WebstormProjects/flow-swagger/node_modules/json-schema-to-flow-type/lib/index.js:33:194)
    at exports.schemaToFlow.flowSchema (/Users/admin/WebstormProjects/flow-swagger/node_modules/json-schema-to-flow-type/lib/index.js:35:139)
    at /Users/admin/WebstormProjects/flow-swagger/node_modules/lodash/lodash.js:5138:35`

**Comment by benjamine** [comment]
+1, I had to downgrade to 0.2.6

**Comment by wmonk** [comment]
@benjamine @natramov can you provide more information. Would be helpful to have the schema that is causing this issue. Closing until that point.

**Comment by wmonk** [comment]
@benjamine thanks for this, will investigate

**Comment by zhulduz** [comment]
@wmonk Any updates?

**Comment by esturcke** [comment]
Looks like the problem is the `@babel/types` signature for [`objectTypeAnnotation`](https://babeljs.io/docs/en/babel-types#objecttypeannotation) has a new 4th argument. There's an open pull request #28 to address it. I've tested this fix locally and it's working for me.

**Comment by esturcke** [comment]
As a stopgap, @marudor has published [@marudor/json-schema-to-flow-type](https://www.npmjs.com/package/@marudor/json-schema-to-flow-type) with the fix.

**Comment by sakai-akinobu** [comment]
This problem was solved in #28 and v1.0.0 was released.
So I recommend using v1.0.0.
